sudo: false

branches:
  only:
    - sourceCode

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile
  
before_deploy:
  - mkdir -p docs/html
  - echo "$(curl -fsSL https://longshilin.com/files/config.yml)" > docs/html/_config.yml

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: sourceCode

notifications:
  email: false
