sudo: false

branches:
  only:
    - sourceCode

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: false
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: sourceCode

notifications:
  email: false
