var namespace_entitas_1_1_blueprints_1_1_code_generation_1_1_unity_1_1_plugins =
[
    [ "BlueprintDataProvider", "class_entitas_1_1_blueprints_1_1_code_generation_1_1_unity_1_1_plugins_1_1_blueprint_data_provider.html", "class_entitas_1_1_blueprints_1_1_code_generation_1_1_unity_1_1_plugins_1_1_blueprint_data_provider" ]
];