var namespace_desperate_devs_1_1_code_generation_1_1_code_generator_1_1_unity =
[
    [ "Editor", "namespace_desperate_devs_1_1_code_generation_1_1_code_generator_1_1_unity_1_1_editor.html", "namespace_desperate_devs_1_1_code_generation_1_1_code_generator_1_1_unity_1_1_editor" ]
];