var namespace_entitas_1_1_visual_debugging_1_1_code_generation_1_1_plugins =
[
    [ "ContextObserverGenerator", "class_entitas_1_1_visual_debugging_1_1_code_generation_1_1_plugins_1_1_context_observer_generator.html", "class_entitas_1_1_visual_debugging_1_1_code_generation_1_1_plugins_1_1_context_observer_generator" ],
    [ "FeatureClassGenerator", "class_entitas_1_1_visual_debugging_1_1_code_generation_1_1_plugins_1_1_feature_class_generator.html", "class_entitas_1_1_visual_debugging_1_1_code_generation_1_1_plugins_1_1_feature_class_generator" ]
];